CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- NULL for recipes generated by the adaptation chat (no source blog). Postgres
  -- allows multiple NULLs under a UNIQUE constraint, so scraped-recipe dedupe is
  -- unaffected.
  source_url TEXT UNIQUE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  title TEXT NOT NULL,
  image TEXT,
  prep_time TEXT,
  cook_time TEXT,
  servings TEXT,
  ingredients JSONB NOT NULL DEFAULT '[]',
  steps JSONB NOT NULL DEFAULT '[]',
  nutrition JSONB,
  video_url TEXT,
  -- Set when this recipe was produced by adapting another recipe.
  derived_from UUID REFERENCES recipes(id) ON DELETE SET NULL
);
